format = """
$directory\
[](fg:#3c4048 bg:#5ea1ff)\
$git_branch\
$git_status\
[](fg:#5ea1ff bg:#3c4048)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#3c4048 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$character"""

[directory]
style = "fg:#ffffff bg:#3c4048"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#5ea1ff"
format = '[[ $symbol $branch ](fg:#ffffff bg:#5ea1ff)]($style)'

[git_status]
style = "bg:#5ea1ff"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#5ea1ff)]($style)'

[nodejs]
symbol = ""
style = "bg:#3c4048"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#3c4048)]($style)'

[rust]
symbol = ""
style = "bg:#3c4048"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#3c4048)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#3c4048"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#3c4048)]($style)'

[php]
symbol = ""
style = "bg:#3c4048"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#3c4048)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[   $time ](fg:#a0a9cb bg:#1d2230)]($style)'
