return {
  opt = {
    number = true,
    spell = false,
    wrap = true,
    backup = false,
    undofile = true,
    undodir = vim.fn.stdpath "cache" .. "/undo",
    hlsearch = false,
    incsearch = true,
    spelllang = "en",
    showbreak = "↪ ",
    showtabline = 0,
    termguicolors = true,
    tabstop = 2,
    softtabstop = 2,
    shiftwidth = 2,
  },
  g = {
    mapleader = " ",
    autoformat_enabled = true,
    cmp_enabled = true,
    autopairs_enabled = true,
    diagnostics_mode = 3,
    icons_enabled = true,
    ui_notifications_enabled = true,
    colors_name = "nord",
    transparent_enabled = true,
    loaded_syntastic_dart_dartanalyzer_checker = 0,
  },
}
